# Generated by Django 4.0.1 on 2022-01-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('passw', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('skills_req', models.CharField(max_length=200)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('addr', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('addr', models.CharField(max_length=200)),
            ],
        ),
    ]
